### ISSUE TITLE
Question about GPU

### ISSUE THREAD

**Issue by MYMY-young** [ashleykleynhans/llava-docker#10]
Hi, Thanks for sharing the code.

In the ReadMe, "If you select a 13B or larger model, CUDA will result in OOM errors with a GPU that has less than 48GB of VRAM, so A6000 or higher is recommended for 13B.".

If using the A6000, how many A6000 are needed, and approximately how much time does it take for training?

Thanks

**Comment by ashleykleynhans** [comment]
1x A6000 for inference, don't know about training haven't done training, ask in LLaVA repo, this is just a docker container for it.

https://github.com/haotian-liu/LLaVA

**Comment by MYMY-young** [comment]
Thank you for the reply!
