### ISSUE TITLE
Load 4bit Parameter Pass 

### ISSUE THREAD

**Issue by tdilber** [ashleykleynhans/llava-docker#5]
I need to pass --load-4bit parameter for model worker gpu ram usage decrease. Then I try some chippy method but it works :) 

just like: 
docker run -d   --gpus all   -v /workspace   -p 3000:3001   -p 8888:8888 -e MODEL="liuhaotian/llava-v1.5-13b --load-4bit"  ashleykza/llava:latest

FYI

**Comment by ashleykleynhans** [comment]
This is actually more designed for RunPod, I am unable to test it out on Docker locally, but this is useful for people who do want to do so.
